# Generated by Django 2.1.2 on 2018-10-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FilePathField(match='\\.[j|J][p|P][e|E]*[g|G]$', max_length=255, path='/images')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filepopulator.Directory')),
            ],
        ),
    ]
