# Generated by Django 2.1.2 on 2018-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0002_auto_20181010_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='filename',
            field=models.FilePathField(match='\\.[j|J][p|P][e|E]*[g|G]$', max_length=255, path='/images'),
        ),
    ]
