# Generated by Django 2.1.2 on 2018-11-01 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0007_auto_20181101_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='filename',
            field=models.FilePathField(validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.JPG', '.JPEG'], message='Filename must be a JPG')]),
        ),
    ]
