# Generated by Django 2.1.3 on 2018-11-02 01:53

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0009_auto_20181101_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='dateTaken',
            field=models.DateTimeField(default=datetime.datetime(1899, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='filename',
            field=models.FilePathField(max_length=255, validators=[django.core.validators.RegexValidator(message='Filename must be a JPG', regex='\\.[j|J][p|P][e|E]*[g|G]$')]),
        ),
    ]
