# Generated by Django 2.1.3 on 2018-11-02 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0010_auto_20181102_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='filename',
            field=models.FilePathField(max_length=255, validators=[django.core.validators.RegexValidator(message='Filename must be a JPG', regex='\\.[j|J][p|P][e|E]?[g|G]$')]),
        ),
    ]
