# Generated by Django 2.1.3 on 2018-11-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0011_auto_20181102_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='dateTakenValid',
            field=models.BooleanField(default=False),
        ),
    ]
