# Generated by Django 2.1.3 on 2018-11-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0012_imagefile_datetakenvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='orientation',
            field=models.IntegerField(default=-8008),
        ),
    ]
