# Generated by Django 2.1.3 on 2018-11-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0013_imagefile_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='thumbnail',
            field=models.ImageField(default='<function now at 0x7f7091a58048>_thumbnail.jpg', upload_to='thumbnails'),
        ),
    ]
