# Generated by Django 2.1.3 on 2018-11-03 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0014_imagefile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='id',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='image_hash',
            field=models.CharField(default=-1, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='filename',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Filename must be a JPG', regex='\\.[j|J][p|P][e|E]?[g|G]$')]),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
